(part "OPA350UA_2K5"
    (packageRef "SOIC127P600X175-8N")
    (interface
        (port "1" (symbPinId 1) (portName "NC_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "-IN") (portType INOUT))
        (port "3" (symbPinId 3) (portName "+IN") (portType INOUT))
        (port "4" (symbPinId 4) (portName "V-") (portType INOUT))
        (port "5" (symbPinId 5) (portName "NC_2") (portType INOUT))
        (port "6" (symbPinId 6) (portName "OUTPUT") (portType INOUT))
        (port "7" (symbPinId 7) (portName "V+") (portType INOUT))
        (port "8" (symbPinId 8) (portName "NC_3") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "OPA350UA/2K5")
    (property "Mouser_Part_Number" "595-OPA350UA/2K5")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/OPA350UA-2K5?qs=7nS3%252BbEUL6sT6%2Fm03FwKkQ%3D%3D")
    (property "Arrow_Part_Number" "OPA350UA/2K5")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/opa350ua2k5/texas-instruments?region=nac")
    (property "Description" "High-Speed, Single-Supply, Rail-to-Rail Operational Amplifiers MicroAmplifier Series")
    (property "Datasheet_Link" "http://www.ti.com/lit/gpn/OPA350")
    (property "symbolName1" "OPA350UA_2K5")
)
