(part "SMF3_3"
    (packageRef "SOD3718X108N")
    (interface
        (port "1" (symbPinId 1) (portName "K") (portType INOUT))
        (port "2" (symbPinId 2) (portName "A") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "LITTELFUSE")
    (property "Manufacturer_Part_Number" "SMF3.3")
    (property "Mouser_Part_Number" "576-SMF3.3")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Littelfuse/SMF3.3?qs=5LChGqRbrjutbyo%2F8EojOg%3D%3D")
    (property "Arrow_Part_Number" "SMF3.3")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/smf3.3/littelfuse?region=nac")
    (property "Description" "ESD Suppressors / TVS Diodes 200W 3.3V 5% Uni-directional")
    (property "Datasheet_Link" "https://componentsearchengine.com/Datasheets/2/SMF3.3.pdf")
    (property "symbolName1" "SMF3_3")
)
