; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
build_flags = 
    -I include
    -Wno-unknown-pragmas ; <-- suppresses the pragma region warnings
lib_deps = 
    https://github.com/nRF24/RF24
    ; https://github.com/greiman/SdFat
    https://github.com/wollewald/ICM20948_WE
    https://github.com/mikalhart/TinyGPSPlus
    https://github.com/PaulStoffregen/PWMServo
    https://github.com/adafruit/Adafruit_BNO08x
    ; https://github.com/micro-ROS/micro_ros_platformio
    https://github.com/khoih-prog/TimerInterrupt_Generic
    https://github.com/milesburton/Arduino-Temperature-Control-Library
check_tool = clangtidy
extra_scripts = pre:print_size.py