M48
; DRILL file {KiCad 9.0.7+1} date 2026-03-01T17:30:14+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-01T17:30:14+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7+1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.000
%
G90
G05
T1
X124.0Y-99.5
X175.0Y-99.5
T2
X124.0Y-84.0
X124.0Y-115.0
X175.0Y-84.0
X175.0Y-115.0
M30
