[platformio]
default_envs = teensy41_i2c
 
 
[env:teensy41_uart]
platform = teensy
board = teensy41
framework = arduino
targets = upload
 
build_flags =
    -DUSE_UART
 
lib_deps =
    stevemarple/MicroNMEA @ ^2.0.6
 
monitor_speed = 115200
 
 
[env:teensy41_i2c]
platform = teensy
board = teensy41
framework = arduino
targets = upload
 
build_flags =
    -DUSE_I2C
 
lib_deps =
    stevemarple/MicroNMEA @ ^2.0.6
 
monitor_speed = 115200