(part "VSSAF5M10-M3_H"
    (packageRef "SODFL5226X100N")
    (interface
        (port "1" (symbPinId 1) (portName "K") (portType INOUT))
        (port "2" (symbPinId 2) (portName "A") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "Vishay")
    (property "Manufacturer_Part_Number" "VSSAF5M10-M3/H")
    (property "Mouser_Part_Number" "78-VSSAF5M10-M3/H")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Vishay-General-Semiconductor/VSSAF5M10-M3-H?qs=ECv811tYSNgAKxXn4qJoLg%3D%3D")
    (property "Arrow_Part_Number" "VSSAF5M10-M3/H")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/vssaf5m10-m3h/vishay?region=nac")
    (property "Description" "Schottky Diodes & Rectifiers TMBS 100V Vrrm eSMP SlimSMA (DO-221AC)")
    (property "Datasheet_Link" "https://www.mouser.co.uk/datasheet/2/427/VISH_S_A0006177028_1-2569585.pdf")
    (property "symbolName1" "VSSAF5M10-M3_H")
)
