(part "TC33X-2-104E"
    (packageRef "TC33X2503E")
    (interface
        (port "1" (symbPinId 1) (portName "CCW") (portType INOUT))
        (port "2" (symbPinId 2) (portName "WIPER") (portType INOUT))
        (port "3" (symbPinId 3) (portName "CW") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "Bourns")
    (property "Manufacturer_Part_Number" "TC33X-2-104E")
    (property "Mouser_Part_Number" "652-TC33X-2-104E")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Bourns/TC33X-2-104E?qs=2hAPiALdQ0llyX8B3WfcDg%3D%3D")
    (property "Arrow_Part_Number" "TC33X-2-104E")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/tc33x-2-104e/bourns?utm_currency=USD&region=nac")
    (property "Description" "Cermet 3mm SMT trimmer,0.1W 100k Bourns TC33 Series SMD Cermet Trimmer Resistor with Solder Pad Terminations, 100k +/-25% 1/10W +/-250ppm/C Top Adjust")
    (property "Datasheet_Link" "https://www.bourns.com/pdfs/TC33.pdf")
    (property "symbolName1" "TC33X-2-104E")
)
